apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-fibonacci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-fibonacci
  template:
    metadata:
        labels:
          app: go-fibonacci
          tag: fibonacci
    spec:
      containers:
      - name: go-fibonacci
        image: ylasmak/go-fibonacci:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"
            cpu: "400m"
          requests:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          timeoutSeconds: 120
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          timeoutSeconds: 120
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3



